### ISSUE TITLE
URLs with fragments without a leading '/' not supported

### ISSUE THREAD

**Issue by vmalloc** [johno/ember-linkify#30]
It seems like http://some.website.com#fragment URLs are not properly parsed, although they are allowed according to the URI specifications.

**Comment by vmalloc** [comment]
@dnstld I will try to find some time to play with it. If I manage to craft a working PR I'll gladly open it.

**Comment by vmalloc** [comment]
@dnstld I created a pull request (#38) - the tests seem to pass, including the one I added for this case.
Let me know if you have any reservations/comments about it.

Thanks!

**Comment by dnstld** [comment]
Seem okay @vmalloc 
Thank you too
It will be updated as soon as possible
